name: TEST
on:
  push:
    branches:
      - main

jobs:
  test: 
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: mkdir -p build
      - name: base test case
        id: ejs
        uses: ./
        with:
          template: <h1><%= name %> <div><%= conclusion %><div></h1>
          vars: |
            { "name": "${{ github.repository }}", "conclusion": "${{ steps.ejs.conclusion }}" }
      
      - name: process.env & context test case
        uses: ./
        with:
          template: |
            <h1><%= process.env.GITHUB_REF %></h1> commiter: <%= context.payload.head_commit.author.name %>
      
      - run: cat build/index.html
      - run: echo "${{ steps.ejs.outputs.content }}"
