name: TEST
on:
  push:
    branches:
      - main

jobs:
  test: 
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: mkdir -p build/template

      - name: ⛑ -> base
        id: ejs
        uses: ./
        with:
          template: <h1><%= name %></h1>
          vars: |
            { "name": "${{ github.repository }}" }
      
      - run: cat build/index.html
      - run: echo "${{ steps.ejs.outputs.content }}"
      
      - name: ⛑ -> process.env & context
        uses: ./
        with:
          template: |
            <h1><%= env.GITHUB_REF %></h1> commiter: <%= context.payload.head_commit.author.name %>
          output: build/test2.html
      - run: cat build/test2.html

      - name: ⛑ -> template-file
        uses: ./
        with:
          template-file: template/demo.html
          output: build/template/demo.html
          vars: |
            {
              "htmlContent": "${{ steps.ejs.outputs.content }}"
            }
      - run: cat build/template/demo.html

      - name: ⛑ -> vars-file
        uses: ./
        with:
          template: <div><%= LICENSE %></div><div><%= markdown %></div>
          output: build/demo.html
          vars-file: |
            - markdown: ./README.md
            - LICENSE: ./LICENSE

      - run: cat build/demo.html
